_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 782137ee-40a5-4311-9ae5-6c3e6e0b385b
name: 'Drupal Demo'
mail: sergey.gabrielyan1998@gmail.com
slogan: ''
page:
  403: ''
  404: ''
  front: /user/login
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
